import os
import sys
import argparse
import subprocess
import rasterio
import datetime
import shutil
import pyproj
import numpy as np
import pandas as pd

def get_paths(year):
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
    data_gen_dir = os.path.join(base_dir, "Data Generation Pipeline")
    start_date = f"{year}-06-01"
    end_date = f"{year}-09-01"
    
    # Download script runs from data_gen_dir, creating data/sentinel2_downloads_...
    download_folder = os.path.join(data_gen_dir, "data", f"sentinel2_downloads_{start_date}_{end_date}")
    features_out_dir = os.path.join(download_folder, "Features")
    
    # Files generated by the download script
    s2rgbnir_tif = os.path.join(download_folder, "Nuremberg_S2RGBNIR.tif")
    ndvi_tif = os.path.join(download_folder, "Nuremberg_NDVI.tif")
    swir_tif = os.path.join(download_folder, "Nuremberg_SWIR.tif")
    
    return {
        'base_dir': base_dir,
        'data_gen_dir': data_gen_dir,
        'start_date': start_date,
        'end_date': end_date,
        'download_folder': download_folder,
        'features_out_dir': features_out_dir,
        's2rgbnir_tif': s2rgbnir_tif,
        'ndvi_tif': ndvi_tif,
        'swir_tif': swir_tif,
        'stacked_tif': os.path.join(features_out_dir, f"stacked_9band_{year}.tif"),
        'grid_csv': os.path.join(features_out_dir, f"grid_{year}.csv"),
        'features_csv': os.path.join(features_out_dir, f"features_{year}.csv"),
        'metadata_md': os.path.join(features_out_dir, "dataset_metadata.md")
    }

def run_download(paths):
    print(f"\n--- [1/4] Checking Sentinel-2 data for {paths['start_date']} to {paths['end_date']} ---")
    if os.path.exists(paths['s2rgbnir_tif']) and os.path.exists(paths['ndvi_tif']) and os.path.exists(paths['swir_tif']):
        print("Data already exists. Skipping download.")
        return

    script_path = os.path.join("..", "src", "download_sentinel2_ee.py")
    cmd = [
        sys.executable, script_path,
        "--start_date", paths['start_date'],
        "--end_date", paths['end_date']
    ]
    
    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=paths['data_gen_dir'])
    if result.returncode != 0:
        print("Error: Download script failed!")
        sys.exit(1)

def stack_bands(paths):
    print("\n--- [2/4] Stacking bands for feature extraction ---")
    os.makedirs(paths['features_out_dir'], exist_ok=True)
    
    if os.path.exists(paths['stacked_tif']):
        print(f"Stacked TIF already exists at {paths['stacked_tif']}. Skipping stacking.")
        return paths['stacked_tif']
        
    print("Reading source bands...")
    try:
        with rasterio.open(paths['s2rgbnir_tif']) as src1, \
             rasterio.open(paths['ndvi_tif']) as src2, \
             rasterio.open(paths['swir_tif']) as src3:
             
            meta = src1.meta.copy()
            meta.update({
                'count': 9,  # We need exactly 9 bands (3 from each)
                'dtype': 'uint8'
            })
            
            with rasterio.open(paths['stacked_tif'], 'w', **meta) as dst:
                print("Writing RGB bands (1-3)...")
                dst.write(src1.read(1), 1)
                dst.write(src1.read(2), 2)
                dst.write(src1.read(3), 3)
                
                print("Writing NDVI bands (4-6)...")
                dst.write(src2.read(1), 4)
                dst.write(src2.read(2), 5)
                dst.write(src2.read(3), 6)
                
                print("Writing SWIR bands (7-9)...")
                dst.write(src3.read(1), 7)
                dst.write(src3.read(2), 8)
                dst.write(src3.read(3), 9)
                
        print(f"Successfully created stacked 9-band TIF at {paths['stacked_tif']}")
        return paths['stacked_tif']
    except Exception as e:
        print(f"Error stacking bands: {e}")
        sys.exit(1)

def create_grid_csv(paths, grid_size):
    print(f"\n--- [2.5/4] Generating Dynamic Grid ({grid_size}m) ---")
    if os.path.exists(paths['grid_csv']):
        print(f"Grid CSV already exists at {paths['grid_csv']}. Skipping generation.")
        return paths['grid_csv']

    with rasterio.open(paths['stacked_tif']) as src:
        transform = src.transform
        width = src.width
        height = src.height

    P = max(1, grid_size // 10)
    num_rows = int(np.ceil(height / P))
    num_cols = int(np.ceil(width / P))

    proj = pyproj.Transformer.from_crs("EPSG:3857", "EPSG:4326", always_xy=True)

    rows = []
    cell_id = 0
    
    for r in range(num_rows):
        for c in range(num_cols):
            r_start = r * P
            r_end = min((r + 1) * P, height)
            c_start = c * P
            c_end = min((c + 1) * P, width)
            
            if r_start >= r_end or c_start >= c_end:
                continue

            minx = transform.c + c_start * transform.a
            maxy = transform.f + r_start * transform.e
            maxx = transform.c + c_end * transform.a
            miny = transform.f + r_end * transform.e

            lon_min, lat_min = proj.transform(minx, miny)
            lon_max, lat_max = proj.transform(maxx, maxy)

            rows.append({
                "cell_id": cell_id,
                "row": r,
                "col": c,
                "min_lon": lon_min,
                "min_lat": lat_min,
                "max_lon": lon_max,
                "max_lat": lat_max,
                "grid_size_m": grid_size
            })
            cell_id += 1

    df = pd.DataFrame(rows)
    df.to_csv(paths['grid_csv'], index=False)
    print(f"Grid CSV generated successfully with {len(df)} cells.")
    return paths['grid_csv']

def run_extraction(paths, year):
    print("\n--- [3/4] Running Feature Extraction ---")
    script_path = os.path.join("src", "extract_features_cli.py")
    cmd = [
        sys.executable, script_path,
        "--csv_path", paths['grid_csv'],
        "--tif_path", paths['stacked_tif'],
        "--out_csv", paths['features_csv'],
        "--tag", str(year)
    ]
    
    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=paths['data_gen_dir'])
    if result.returncode != 0:
        print("Error: Feature extraction failed!")
        sys.exit(1)
        
    # Clean up the temporary stacked tif to save space
    if os.path.exists(paths['stacked_tif']):
        print("Cleaning up temporary stacked TIF...")
        os.remove(paths['stacked_tif'])

def generate_metadata(paths, grid_size, year):
    print("\n--- [4/4] Writing Metadata ---")
    
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    md_content = f"""# Feature Extraction Metadata
    
**Year**: {year}
**Date Generated**: {now}

## Data Sources
- **Sentinel-2 Date Range**: {paths['start_date']} to {paths['end_date']}
- **Geographic Grid Definitions**: Dynamically generated ({grid_size}m grid cells) saved at `{paths['grid_csv']}`

## Outputs
- **Features CSV**: `{paths['features_csv']}`

## Scripts Used
- Data Downloaded via: `src/download_sentinel2_ee.py`
- Features Extracted via: `Data Generation Pipeline/src/extract_features_cli.py` (which matches `FeatureExtraction.ipynb` logic identically)
- Pipeline Orchestration: `Data Generation Pipeline/src/orchestrate_features.py`

## Band Stack Structure (9-Bands)
During extraction, a temporary 9-band combination was merged and analyzed:
1. S2_R (from Sentinel-2)
2. S2_G (from Sentinel-2)
3. S2_B (from Sentinel-2)
4. NDVI_1 (from Earth Engine visual composite)
5. NDVI_2 (from Earth Engine visual composite)
6. NDVI_3 (from Earth Engine visual composite)
7. SWIR_1 (from Earth Engine visual composite)
8. SWIR_2 (from Earth Engine visual composite)
9. SWIR_3 (from Earth Engine visual composite)
"""
    with open(paths['metadata_md'], 'w') as f:
        f.write(md_content)
    
    print(f"Metadata written successfully to {paths['metadata_md']}")

def main():
    parser = argparse.ArgumentParser(description="Orchestrate finding/downloading Sentinel-2 data and calculating features.")
    parser.add_argument("--year", type=int, required=True, help="Target year to calculate features for (e.g. 2022).")
    parser.add_argument("--grid_size", type=int, default=1000, help="Grid size in meters (default: 1000).")
    args = parser.parse_args()
    
    paths = get_paths(args.year)
    
    try:
        run_download(paths)
        stack_bands(paths)
        create_grid_csv(paths, args.grid_size)
        run_extraction(paths, args.year)
        generate_metadata(paths, args.grid_size, args.year)
        print("\n=== PIPELINE SUCCESSFUL ===")
        print(f"Features mapped and stored at: {paths['features_csv']}")
    except KeyboardInterrupt:
        print("\nProcess interrupted by user.")
        sys.exit(1)

if __name__ == "__main__":
    main()
